// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fnmxgzzxloyqkemlizdu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZubXhnenp4bG95cWtlbWxpemR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MzI4ODAsImV4cCI6MjA2NjUwODg4MH0.sumi__ohntiLo79Z5OXPA8AE0z-Ud5SitCn86XewQ28";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);